from app.schemas import TestStep as StepSchema
from app.services.ai_service import (
    _normalize_ai_steps,
    generate_test_case,
    generate_test_suite,
    is_suite_request,
)


def test_automatic_suite_uses_detected_major_features(monkeypatch):
    monkeypatch.setattr("app.services.ai_service.llm_status", lambda: {"available": False})
    monkeypatch.setattr(
        "app.services.ai_service.inspect_page",
        lambda target_url: {
            "title": "Demo Shop",
            "inputs": [
                {"selector": "input[type=search]", "type": "search", "name": "q", "placeholder": "Search"},
                {"selector": "input[name=name]", "type": "text", "name": "name", "placeholder": "Name"},
            ],
            "buttons": [{"selector": "button[aria-label=menu]", "text": "Menu"}],
            "links": [{"selector": "a", "text": "Products", "href": "https://example.com/products"}],
            "headings": ["Welcome"],
            "media": [{"selector": "img", "type": "img", "label": "Product"}],
            "error": "",
        },
    )

    suite = generate_test_suite("https://example.com")
    names = [test["name"] for test in suite["tests"]]
    action_sets = [tuple(step.action for step in test["steps"]) for test in suite["tests"]]

    assert len(names) >= 6
    assert len(names) == len(set(names))
    assert len(action_sets) == len(set(action_sets))
    assert "search" in suite["detected_features"]
    assert "navigation" in suite["detected_features"]
    assert "interactive controls" in suite["detected_features"]


def test_blank_suite_uses_qwen_when_available(monkeypatch):
    monkeypatch.setattr("app.services.ai_service.llm_status", lambda: {"available": True})
    monkeypatch.setattr(
        "app.services.ai_service.inspect_page",
        lambda target_url: {
            "title": "Demo",
            "inputs": [],
            "buttons": [],
            "links": [],
            "headings": [],
            "media": [],
            "error": "",
        },
    )
    cases = []
    for index in range(5):
        cases.append(
            {
                "name": f"Qwen case {index}",
                "intent_summary": "Generated by Qwen.",
                "expected_result": "The behavior is verified.",
                "test_data": {"other": {}},
                "steps": [
                    {"action": "goto", "description": "Open site."},
                    {"action": "assert_title", "description": "Verify title."},
                    {"action": "assert_visible", "selector": "body", "description": "Verify body."},
                    {"action": "wait", "value": "100", "description": "Wait."},
                    {"action": "screenshot", "description": "Capture evidence."},
                ],
            }
        )

    captured = {}
    def fake_chat_json(system, user, **kwargs):
        captured["user"] = user
        return {"page_title": "Demo", "detected_features": ["qwen"], "tests": cases}

    monkeypatch.setattr("app.services.ai_service.chat_json", fake_chat_json)

    suite = generate_test_suite("https://example.com")

    assert suite["tests"][0]["generation_source"] == "qwen-ai"
    assert "complete functional test suite" in captured["user"]


def test_youtube_suite_avoids_treating_search_as_plain_form(monkeypatch):
    monkeypatch.setattr("app.services.ai_service.llm_status", lambda: {"available": False})
    monkeypatch.setattr(
        "app.services.ai_service.inspect_page",
        lambda target_url: {
            "title": "YouTube",
            "inputs": [{"selector": 'input[name="search_query"]', "type": "text", "name": "search_query", "placeholder": "Search"}],
            "buttons": [{"selector": "button#guide", "text": "Guide"}],
            "links": [],
            "headings": ["Try searching to get started"],
            "media": [],
            "error": "",
        },
    )

    suite = generate_test_suite("https://www.youtube.com/")
    names = [test["name"].lower() for test in suite["tests"]]

    assert any("search results" in name for name in names)
    assert any("video playback search" in name for name in names)
    assert not any("form input" in name for name in names)


def test_ecommerce_suite_includes_safe_product_discovery(monkeypatch):
    monkeypatch.setattr("app.services.ai_service.llm_status", lambda: {"available": False})
    monkeypatch.setattr(
        "app.services.ai_service.inspect_page",
        lambda target_url: {
            "title": "Flipkart",
            "inputs": [{"selector": "input[name=q]", "type": "text", "name": "q", "placeholder": "Search for Products"}],
            "buttons": [{"selector": "button.cart", "text": "Cart"}],
            "links": [{"selector": "a.product", "text": "Mobiles", "href": "https://www.flipkart.com/mobiles"}],
            "headings": [],
            "media": [{"selector": "img.product", "type": "img", "label": "Product"}],
            "error": "",
        },
    )

    suite = generate_test_suite("https://www.flipkart.com/")
    product_case = next(test for test in suite["tests"] if "product discovery" in test["name"].lower())
    text = str(product_case).lower()

    assert "ecommerce product discovery" in suite["detected_features"]
    assert "laptop" in text
    assert "checkout" in product_case["expected_result"].lower()
    assert "payment" in product_case["expected_result"].lower()


def test_streaming_suite_includes_safe_media_entry_point(monkeypatch):
    monkeypatch.setattr("app.services.ai_service.llm_status", lambda: {"available": False})
    monkeypatch.setattr(
        "app.services.ai_service.inspect_page",
        lambda target_url: {
            "title": "Netflix",
            "inputs": [],
            "buttons": [{"selector": "button.play", "text": "Play"}],
            "links": [{"selector": "a.login", "text": "Sign In", "href": "https://www.netflix.com/login"}],
            "headings": ["Unlimited movies"],
            "media": [{"selector": "img.hero", "type": "img", "label": "Show"}],
            "error": "",
        },
    )

    suite = generate_test_suite("https://www.netflix.com/")
    names = [test["name"].lower() for test in suite["tests"]]

    assert any("media playback entry point" in name for name in names)
    assert any("sign-in guardrail" in name for name in names)


def test_prompt_search_preserves_exact_requested_keyword_and_is_deep(monkeypatch):
    monkeypatch.setattr("app.services.ai_service.llm_status", lambda: {"available": False})
    monkeypatch.setattr(
        "app.services.ai_service.inspect_page",
        lambda target_url: {
            "title": "YouTube",
            "inputs": [
                {
                    "selector": 'input[name="search_query"]',
                    "type": "text",
                    "name": "search_query",
                    "placeholder": "Search",
                }
            ],
            "buttons": [],
            "links": [],
            "headings": [],
            "media": [],
            "error": "",
        },
    )

    case = generate_test_case(
        "https://www.youtube.com/",
        "can you test by searching for a 4k",
    )
    actions = [step.action for step in case["steps"]]
    filled_values = [step.value for step in case["steps"] if step.action == "fill"]

    assert filled_values == ["4k"]
    assert len(case["steps"]) >= 12
    assert "assert_value" in actions
    assert "assert_count" in actions
    assert "click" not in actions
    assert actions.count("assert_url_contains") >= 1
    assert "playwright test automation" not in str(case)


def test_search_prompt_opens_result_only_when_requested(monkeypatch):
    monkeypatch.setattr("app.services.ai_service.llm_status", lambda: {"available": False})
    monkeypatch.setattr(
        "app.services.ai_service.inspect_page",
        lambda target_url: {
            "title": "YouTube",
            "inputs": [{"selector": "#search", "type": "search", "name": "search", "placeholder": "Search"}],
            "buttons": [],
            "links": [],
            "headings": [],
            "media": [],
            "error": "",
        },
    )

    case = generate_test_case(
        "https://www.youtube.com/",
        "search for 8k nature video then open the first result and verify it plays",
    )
    actions = [step.action for step in case["steps"]]
    fill_step = next(step for step in case["steps"] if step.action == "fill")

    assert fill_step.value == "8k nature video"
    assert "click" in actions
    assert actions.count("assert_url_contains") >= 2


def test_search_prompt_separates_keyword_from_expected_result_language(monkeypatch):
    monkeypatch.setattr("app.services.ai_service.llm_status", lambda: {"available": False})
    monkeypatch.setattr(
        "app.services.ai_service.inspect_page",
        lambda target_url: {
            "title": "YouTube",
            "inputs": [
                {
                    "selector": 'input[name="search_query"]',
                    "type": "text",
                    "name": "search_query",
                    "placeholder": "Search",
                }
            ],
            "buttons": [],
            "links": [],
            "headings": [],
            "media": [],
            "error": "",
        },
    )

    case = generate_test_case(
        "https://www.youtube.com/",
        "search for 8k video and see you are seeing the expected output",
    )
    fill_step = next(step for step in case["steps"] if step.action == "fill")
    actions = [step.action for step in case["steps"]]

    assert fill_step.value == "8k video"
    assert case["name"] == "Search YouTube for 8k video and verify results"
    assert "click" not in actions
    assert "expected output" not in str(case["steps"]).lower()


def test_youtube_login_prompt_navigates_to_google_before_entering_dummy_account(monkeypatch):
    monkeypatch.setattr("app.services.ai_service.llm_status", lambda: {"available": False})
    monkeypatch.setattr(
        "app.services.ai_service.inspect_page",
        lambda target_url: {
            "title": "YouTube",
            "inputs": [],
            "buttons": [],
            "links": [],
            "headings": [],
            "media": [],
            "error": "",
        },
    )

    case = generate_test_case(
        "https://www.youtube.com/",
        "try to sign in with dummy credentials and verify it does not log in",
    )
    actions = [step.action for step in case["steps"]]
    fill_steps = [step for step in case["steps"] if step.action == "fill"]

    assert case["name"] == "Verify YouTube rejects invalid sign-in credentials"
    assert actions[:5] == ["goto", "assert_visible", "click", "wait", "assert_url_contains"]
    assert fill_steps[0].value.endswith(".invalid")
    assert all("password" not in (step.selector or "") for step in fill_steps)
    assert actions.count("assert_url_contains") == 2
    assert any(
        "rejection message" in step.description.lower()
        for step in case["steps"]
        if step.action == "assert_visible"
    )


def test_youtube_quality_prompt_generates_resolution_workflow(monkeypatch):
    monkeypatch.setattr("app.services.ai_service.llm_status", lambda: {"available": False})
    monkeypatch.setattr(
        "app.services.ai_service.inspect_page",
        lambda target_url: {
            "title": "YouTube",
            "inputs": [{"selector": 'input[name="search_query"]', "type": "text", "name": "search_query", "placeholder": "Search"}],
            "buttons": [],
            "links": [],
            "headings": [],
            "media": [],
            "error": "",
        },
    )

    case = generate_test_case(
        "https://www.youtube.com/",
        "test quality of video by toggling all resolutions",
    )
    actions = [step.action for step in case["steps"]]

    assert case["name"] == "Verify YouTube video quality options can be changed"
    assert "youtube_cycle_quality" in actions
    assert "click" in actions
    assert any(step.selector == "#movie_player, video" for step in case["steps"])
    assert "quality/resolution" in case["expected_result"]


def test_login_plan_uses_non_search_account_input_and_otp_button():
    page_context = {
        "inputs": [
            {"selector": 'input[name="q"]', "type": "text", "name": "q", "placeholder": "Search"},
            {"selector": 'input[type="text"]', "type": "text", "name": "", "placeholder": ""},
        ],
        "buttons": [{"selector": 'button[type="submit"]', "text": "Request OTP"}],
        "links": [{"selector": "a", "text": "Login", "href": "https://www.flipkart.com/account/login"}],
    }
    steps = [
        StepSchema(action="click", selector="a", description="Click the Login link to navigate to login page"),
        StepSchema(action="fill", selector='input[name="username"]', value="invalid", description="Enter invalid username"),
        StepSchema(action="fill", selector='input[name="password"]', value="invalid", description="Enter password"),
        StepSchema(action="click", selector='button[type="submit"]', description="Submit login form"),
    ]

    normalized = _normalize_ai_steps(
        steps,
        {"action": "negative_login", "test_data": {}},
        page_context,
        "https://www.flipkart.com/account/login",
    )

    assert normalized[0].selector == "text=/^Login$/i"
    assert normalized[1].selector == 'input[type="text"]'
    assert normalized[2].optional is True
    assert normalized[3].selector == "text=/^Request\\ OTP$/i"


def test_prompt_generation_uses_ai_intent_and_plan_before_fallback(monkeypatch):
    monkeypatch.setattr("app.services.ai_service.llm_status", lambda: {"available": True})
    monkeypatch.setattr(
        "app.services.ai_service.inspect_page",
        lambda target_url: {
            "title": "Demo",
            "inputs": [{"selector": "#query", "type": "search", "name": "query", "placeholder": "Search"}],
            "buttons": [],
            "links": [],
            "headings": [],
            "media": [],
            "error": "",
        },
    )
    responses = iter(
        [
            {
                "action": "search",
                "objective": "Search for solar eclipses and verify results.",
                "test_data": {"search_query": "solar eclipses", "username": "", "other": {}},
                "requested_actions": ["search"],
                "expected_outcomes": ["results are visible"],
                "safety_constraints": [],
                "ambiguities": [],
            },
            {
                "name": "AI search validation",
                "intent_summary": "Search for solar eclipses and verify visible results.",
                "expected_result": "Relevant results are shown.",
                "steps": [
                    {"action": "goto", "value": "https://example.com", "description": "Open site."},
                    {"action": "assert_visible", "selector": "#query", "description": "Check search."},
                    {"action": "fill", "selector": "#query", "value": "solar eclipses", "description": "Enter query."},
                    {"action": "assert_value", "selector": "#query", "value": "solar eclipses", "description": "Check query."},
                    {"action": "screenshot", "description": "Capture input."},
                    {"action": "press", "selector": "#query", "value": "Enter", "description": "Submit."},
                    {"action": "wait", "value": "1000", "description": "Wait."},
                    {"action": "assert_visible", "selector": "main a", "description": "Verify results."},
                    {"action": "screenshot", "description": "Capture results."},
                ],
            },
        ]
    )
    monkeypatch.setattr("app.services.ai_service.chat_json", lambda system, user: next(responses))

    case = generate_test_case("https://example.com", "find information about solar eclipses")

    assert case["generation_source"] == "qwen-ai"
    assert case["intent_summary"] == "Search for solar eclipses and verify visible results."
    assert next(step.value for step in case["steps"] if step.action == "fill") == "solar eclipses"


def test_ai_search_plan_repairs_enter_key_selector_to_detected_search_input(monkeypatch):
    monkeypatch.setattr("app.services.ai_service.llm_status", lambda: {"available": True})
    monkeypatch.setattr(
        "app.services.ai_service.inspect_page",
        lambda target_url: {
            "title": "Demo",
            "inputs": [{"selector": "#search-box", "type": "search", "name": "q", "placeholder": "Search"}],
            "buttons": [],
            "links": [],
            "headings": [],
            "media": [],
            "error": "",
        },
    )
    responses = iter(
        [
            {
                "action": "search",
                "objective": "Search for jazz.",
                "test_data": {"search_query": "jazz"},
                "requested_actions": ["search"],
                "expected_outcomes": ["results visible"],
                "safety_constraints": [],
                "ambiguities": [],
            },
            {
                "name": "Search jazz",
                "intent_summary": "Search for jazz.",
                "expected_result": "Results are visible.",
                "steps": [
                    {"action": "goto", "description": "Open."},
                    {"action": "assert_visible", "selector": "#search-box", "description": "Check."},
                    {"action": "fill", "selector": "input", "value": "jazz", "description": "Fill."},
                    {"action": "assert_value", "selector": "#search-box", "value": "jazz", "description": "Confirm."},
                    {"action": "screenshot", "description": "Capture."},
                    {"action": "press", "selector": "button[type=submit]", "value": "Enter", "description": "Submit."},
                    {"action": "wait", "value": "1000", "description": "Wait."},
                    {"action": "assert_visible", "selector": "main a", "description": "Results."},
                ],
            },
        ]
    )
    monkeypatch.setattr("app.services.ai_service.chat_json", lambda system, user: next(responses))

    case = generate_test_case("https://example.com", "find jazz")
    press_step = next(step for step in case["steps"] if step.action == "press")

    assert press_step.selector == "#search-box"


def test_ai_search_placeholder_check_is_grounded_to_detected_input(monkeypatch):
    monkeypatch.setattr("app.services.ai_service.llm_status", lambda: {"available": True})
    monkeypatch.setattr(
        "app.services.ai_service.inspect_page",
        lambda target_url: {
            "title": "YouTube",
            "inputs": [{"selector": 'input[name="search_query"]', "type": "text", "name": "search_query", "placeholder": "Search"}],
            "buttons": [],
            "links": [],
            "headings": [],
            "media": [],
            "error": "",
        },
    )
    responses = iter(
        [
            {
                "action": "search",
                "objective": "Verify search box.",
                "test_data": {"search_query": "minimal query"},
                "requested_actions": ["search"],
                "expected_outcomes": ["results visible"],
                "safety_constraints": [],
                "ambiguities": [],
            },
            {
                "name": "Verify YouTube Search Box Functionality",
                "intent_summary": "Verify search.",
                "expected_result": "Results are visible.",
                "steps": [
                    {"action": "goto", "value": "https://youtube.com/", "description": "Navigate to YouTube homepage"},
                    {"action": "assert_visible", "selector": "input", "description": "Check search box is visible on homepage"},
                    {"action": "assert_text", "value": "Search", "description": "Verify placeholder text matches expected 'Search'"},
                    {"action": "fill", "selector": "input", "value": "minimal query", "description": "Enter query"},
                    {"action": "press", "selector": "input", "value": "Enter", "description": "Submit search"},
                    {"action": "wait", "value": "1000", "description": "Wait"},
                    {"action": "assert_visible", "selector": "a", "description": "Check search results are visible"},
                    {"action": "screenshot", "description": "Capture screenshot"},
                ],
            },
        ]
    )
    monkeypatch.setattr("app.services.ai_service.chat_json", lambda system, user, **kwargs: next(responses))

    case = generate_test_case("https://youtube.com/", "test search box")
    placeholder_step = case["steps"][2]

    assert placeholder_step.action == "assert_visible"
    assert placeholder_step.selector == 'input[name="search_query"]'
    assert placeholder_step.value is None


def test_ai_youtube_plan_grounds_invented_result_and_player_selectors(monkeypatch):
    monkeypatch.setattr("app.services.ai_service.llm_status", lambda: {"available": True})
    monkeypatch.setattr(
        "app.services.ai_service.inspect_page",
        lambda target_url: {
            "title": "YouTube",
            "inputs": [{"selector": "#search", "type": "search", "name": "search_query", "placeholder": "Search"}],
            "buttons": [],
            "links": [],
            "headings": [],
            "media": [],
            "error": "",
        },
    )
    responses = iter(
        [
            {
                "action": "search_and_open",
                "objective": "Search and open a video.",
                "test_data": {"search_query": "lofi"},
                "requested_actions": ["open first result"],
                "expected_outcomes": ["video player visible"],
                "safety_constraints": [],
                "ambiguities": [],
            },
            {
                "name": "Open lofi",
                "intent_summary": "Search lofi and open the first result.",
                "expected_result": "Player is visible.",
                "steps": [
                    {"action": "goto", "description": "Open."},
                    {"action": "assert_visible", "selector": "#search", "description": "Check search."},
                    {"action": "fill", "selector": "#search", "value": "lofi", "description": "Fill."},
                    {"action": "press", "selector": "button", "value": "Enter", "description": "Search."},
                    {"action": "wait", "value": "1000", "description": "Wait."},
                    {"action": "assert_visible", "selector": "a[href*=lofi]", "description": "Verify a video result."},
                    {"action": "click", "selector": "a[href*=lofi]", "description": "Open first video result."},
                    {"action": "wait", "value": "1000", "description": "Wait."},
                    {"action": "assert_visible", "selector": ".invented-player", "description": "Verify video player."},
                ],
            },
        ]
    )
    monkeypatch.setattr("app.services.ai_service.chat_json", lambda system, user: next(responses))

    case = generate_test_case("https://www.youtube.com", "find lofi and open the first video")
    result_check = next(step for step in case["steps"] if "video result" in step.description.lower())
    result_click = next(step for step in case["steps"] if step.action == "click")
    player_check = next(step for step in case["steps"] if "video player" in step.description.lower())

    assert result_check.selector == "ytd-video-renderer a#video-title, ytd-rich-item-renderer a#video-title"
    assert result_click.selector == result_check.selector
    assert player_check.selector == "#movie_player, video"


def test_generate_all_functional_tests_is_detected_as_suite_request():
    assert is_suite_request("Generate all functional tests")
    assert is_suite_request("Create a complete regression suite")
    assert not is_suite_request("Search for a laptop")


def test_ai_functional_suite_returns_multiple_distinct_cases(monkeypatch):
    monkeypatch.setattr("app.services.ai_service.llm_status", lambda: {"available": True})
    monkeypatch.setattr(
        "app.services.ai_service.inspect_page",
        lambda target_url: {
            "title": "Demo Store",
            "inputs": [{"selector": "#search", "type": "search", "name": "q", "placeholder": "Search"}],
            "buttons": [{"selector": "#menu", "text": "Menu"}],
            "links": [{"selector": "a.products", "text": "Products", "href": "https://example.com/products"}],
            "headings": ["Demo Store"],
            "media": [{"selector": "img.product", "type": "img", "label": "Product"}],
            "error": "",
        },
    )
    cases = []
    for index, objective in enumerate(
        ["load page", "search product", "open menu", "navigate products", "view product media"],
        1,
    ):
        cases.append(
            {
                "name": f"Case {index}: {objective}",
                "intent_summary": f"Verify {objective}.",
                "expected_result": f"{objective} works.",
                "test_data": {"search_query": "laptop" if index == 2 else "", "other": {}},
                "steps": [
                    {"action": "goto", "description": "Open site."},
                    {"action": "assert_title", "description": "Verify title."},
                    {"action": "assert_visible", "selector": "body", "description": "Verify page."},
                    {"action": "wait", "value": "100", "description": "Wait."},
                    {"action": "screenshot", "description": "Capture evidence."},
                ],
            }
        )
    cases[0]["steps"] = [
        {"action": "goto", "description": "Open site."},
        {"action": "assert_title", "description": "Verify title."},
        {"action": "screenshot", "description": "Capture evidence."},
    ]
    cases[1]["steps"][2]["selector"] = 'a[text="Products"]'
    monkeypatch.setattr(
        "app.services.ai_service.chat_json",
        lambda system, user, **kwargs: {
            "page_title": "Demo Store",
            "detected_features": ["availability", "search", "menu", "navigation", "media"],
            "tests": cases,
        },
    )

    suite = generate_test_suite("https://example.com", "Generate all functional tests")

    assert len(suite["tests"]) == 5
    assert all(test["generation_source"] == "qwen-ai" for test in suite["tests"])
    assert all(len(test["steps"]) >= 5 for test in suite["tests"])
    assert suite["tests"][1]["steps"][2].selector == "text=/^Products$/i"
    assert len({test["name"] for test in suite["tests"]}) == 5
